language: node_js
services:
node_js:
  - 0.10
before_install:
  - sudo apt-get install libzmq3-dev
before_script:
  - npm install -g grunt-cli
  - npm install -d
branches:
  only:
    - master
script:
  - npm test
after_success:
  - codeclimate < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: nrisfBzNMixOfW8oMtziUlwwY+2+i83Nhhu7O+EXM4+Pk38s7bitYnYDjHu7LSsUZ5rziMsUUiyi8g7yIn6Rkn43jh3z6bHHPt+bzMUT5W0BTrxJP+JnjEMBZ+K206mqkrKdv4c0xFVtKqYLLZ6nFfDw3rsWkeMGHEFm2Iebs+c=
